### ISSUE TITLE
update dependencies?

### ISSUE THREAD

**Issue by bfgray3** [koalaverse/vip#51]
What are your thoughts on using ggplot2 >= 3.0.0, moving dplyr >= 0.7.0 to Imports, and getting rid of plyr (no commits in over two years) and magrittr/tibble (dplyr exports the pipe and `tibble()`) from Imports?  I could do a pull request if you're intersted.

**Comment by bgreenwell** [comment]
Oh boy, lots of thoughts...

* I am reluctant to ever depend on `tidyverse` packages (other than `tibble`--which isn't even necessary here--and `ggplot2`); `tidyverse` packages are great for day-today workflow, but I will go to hell and back to not make those packages a dependency (they change and break way too often).
* Is there any need for `dplyr` functionality or the forward pipe here? I know it's used in the TensorFlow vignette (Side note: I don't think using `%>%` in functions is good practice--but then again, I'm rather old school when it comes to R 😱).
* I know `ggplot2` had a rather large update recently, but does it change any of the code used in this package to force a dependency on the newest version? All the output from `vi()`, `vi_model()`, etc. have consistent column names, so not sure what needs to be changed to satisfy the newest `ggplot2`. But I have no issue with that if it's needed.
* `plyr` is maintained (and should always be around). I like `plyr` because it is the most straightforward way to use apply-like functions with options for parallel processing based on `foreach` and `%dopar%` (which is certainly needed for `vint()`) and progress bars. I thought about switching to `purrr`, but not until it supports parallel processing without increasing the dependencies too much.

![2fi2vb](https://user-images.githubusercontent.com/3777755/43841068-408d8c94-9af0-11e8-9ea5-84d7318921af.jpg)

**Comment by bradleyboehmke** [comment]
Don't worry @bfgray3 , if it were up to @bgreenwell everyone would use only base R...and his packages of course!

**Comment by bfgray3** [comment]
Sorry for the delay guys--I've been pretty sick.  I like the meme Brandon.  I too don't like to use the pipe in my package functions.  If it is just used in the vignettes here, I think magrittr can be moved to Suggests from Imports.

**Comment by bgreenwell** [comment]
Ohhhhh, good catch, not sure why `magrittr` is a dependency at all. I can only find its use in the tensorflow vignette which uses `%>%` through `dplyr`. Feel free to change the dependencies to whichever way you think makes most sense!

**Comment by bgreenwell** [comment]
We could also import the pipe operators if we think they'd be useful for the workflow> For example, maybe this:
```r
some_model %>%
  vi(type = "ice") %T>%
  autoplot()  
```
We would need to define an `autoplot.vi()` function that recognizes objects of class `"vi"` (i.e., the outputted tibbles from `vi()`, `vi_model()`, etc.)????
